# Generated by Django 3.1.2 on 2020-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='영화 제목을 입력해 주세요', max_length=50)),
                ('genre', models.CharField(help_text='영화 장르를 입력해 주세요', max_length=20)),
                ('year', models.IntegerField(help_text='제작 년도를 입력해 주세요')),
                ('registration_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
